import streamlit as st

# -----------------------------------------------------
# Page Configuration
# -----------------------------------------------------
st.set_page_config(
    page_title="Mental Health Symptom Severity Predictor",
    layout="wide",
    initial_sidebar_state="expanded"
)

# -----------------------------------------------------
# Title
# -----------------------------------------------------
st.title("Mental Health Symptom Severity Predictor")

st.markdown("""
Welcome to the **Mental Health Symptom Severity Predictor**.

This application demonstrates the machine learning models developed using the
**Transdiagnostic Connectome Project (TCP)** dataset.

The models predict four mental health symptom severity scores:

- **PSS** – Perceived Stress Scale
- **QIDS** – Depression Severity
- **SHAPS** – Anhedonia
- **STAI-State** – State Anxiety

The project compares three approaches:

- Behavioral Features
- Imaging Features
- Multimodal Features (Behavioral + Imaging)

All models were trained using **Random Forest Regression**.
""")

# -----------------------------------------------------
# Quick Summary
# -----------------------------------------------------
st.header("Project Summary")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        label="Prediction Targets",
        value="4"
    )

with col2:
    st.metric(
        label="Models Trained",
        value="28"
    )

with col3:
    st.metric(
        label="Participants",
        value="241"
    )

st.divider()

# -----------------------------------------------------
# Main Findings
# -----------------------------------------------------
st.header("Key Findings")

st.success(""" Behavioral data consistently produced the most accurate predictions.""")
st.info(""" Imaging-only models showed limited predictive performance.""")
st.warning(""" Combining imaging and behavioral data produced little improvement over behavioral data alone.""")

st.divider()

# -----------------------------------------------------
# Best Models
# -----------------------------------------------------
st.header("Best Performing Models")

st.table({
    "Target": [
        "PSS",
        "QIDS",
        "SHAPS",
        "STAI-State"
    ],
    "Best Model": [
        "Behavioral Relevant",
        "Behavioral All",
        "Behavioral Category",
        "Behavioral All"
    ],
    "Test R²": [
        0.674,
        0.642,
        0.295,
        0.719
    ]
})

st.divider()

# -----------------------------------------------------
# Navigation Instructions
# -----------------------------------------------------
st.header("Navigation")

st.markdown("""
Use the **sidebar** to explore the application.

- Predict Symptom Severity
- Model Comparison
- Participant Explorer
- About the Project
""")

st.divider()

# -----------------------------------------------------
# Responsible AI
# -----------------------------------------------------
st.header("Responsible AI")

st.warning("""
This application was developed for educational and research purposes.

Predictions generated by this application are **not medical diagnoses**
and should **not** replace evaluation by a licensed healthcare professional.
""")

# -----------------------------------------------------
# Footer
# -----------------------------------------------------
st.caption("Developed using Python, Streamlit, Scikit-learn, and the Transdiagnostic Connectome Project dataset.")